# -*- coding: utf-8 -*-
"""__init__.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vkbd5tTAyKNnKlhOBUxbYVsSSQTAv42_
"""

from plots import x_y_plot_info